### ISSUE TITLE
🐛 With less-loader: TypeError: this.getLogger is not a function

### ISSUE THREAD

**Issue by KyrieLii** [webpack-contrib/thread-loader#185]
Related to this [issue#10](https://github.com/webpack-contrib/thread-loader/issues/10#issuecomment-1574041975).

- Operating System: macOS 12.5.1
- Node Version: v16.18.0
- NPM Version: 8.19.2
- webpack Version: 5.76.1
- thread-loader Version: 4.0.2

### Expected Behavior

Using with less-loader can work.

### Actual Behavior

Error:

```bash
TypeError: this.getLogger is not a function
    at Object.lessLoader (/xxx/thread-loader-demo/node_modules/.pnpm/less-loader@11.1.2_less@4.1.3+webpack@5.76.1/node_modules/less-loader/dist/index.js:36:23)
    at LOADER_EXECUTION (/xxx/thread-loader-demo/node_modules/.pnpm/loader-runner@4.3.0/node_modules/loader-runner/lib/LoaderRunner.js:132:14)
    at runSyncOrAsync (/xxx/thread-loader-demo/node_modules/.pnpm/loader-runner@4.3.0/node_modules/loader-runner/lib/LoaderRunner.js:133:4)
    at iterateNormalLoaders (/xxx/thread-loader-demo/node_modules/.pnpm/loader-runner@4.3.0/node_modules/loader-runner/lib/LoaderRunner.js:251:2)
    at /xxx/thread-loader-demo/node_modules/.pnpm/loader-runner@4.3.0/node_modules/loader-runner/lib/LoaderRunner.js:224:4
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

### Code

https://github.com/KyrieLii/thread-loader-demo/blob/main/webpack.config.js

### How Do We Reproduce?

```bash
git clone git@github.com:KyrieLii/thread-loader-demo.git

npm i -g pnpm@7

pnpm install

pnpm start
```

**Comment by KyrieLii** [comment]
If nobody follows up, I will attempt to help fix this issue. (when I have time 😂)

**Comment by benjamin-hodgson** [comment]
I fixed this some time ago in https://github.com/webpack-contrib/thread-loader/pull/130, never got merged tho. Feel free to pick up from the work in that PR!

**Comment by alexander-akait** [comment]
@benjamin-hodgson Sorry for delay, let's finish https://github.com/webpack-contrib/thread-loader/pull/130, we need to remap all methods from webpack logger, i.e. webpack logger has `.time()`/`.trace()` and etc methods, so to finish it we need to support all of them, i.e. https://github.com/webpack/webpack/blob/main/lib/logging/Logger.js#L38, thank you
