### ISSUE TITLE
Error with ESLint v9, config ESM: SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by lelelethu** [webpack-contrib/thread-loader#230]
### Bug report
I setting ESLint v9 ESM. 
Trong webpack, sử dụng 'thread-loader', but raise errror: SyntaxError: Cannot use import statement outside a module

### Actual Behavior
webpack.config.mjs
`{
					// Include ts, tsx, js, and jsx files.
					test: /\.(ts|js)x?$/,
					use: [
						 'thread-loader',
						{
							loader: 'babel-loader',
							options: {
								cacheDirectory: true,
								// And replace .babelrc with babel.config.json...
								babelrc: false,
							},
						},
					],
					exclude: /node_modules/,
				},`

Error:
`ERROR in ./src/index.tsx
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
\node_modules\thread-loader\dist\cjs.js:3
import index from './index.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module`

### Expected Behavior
Can support ESM

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
`
ERROR in ./src/index.tsx
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
D:\Project\CTG\kv-retail-report-widget-3\node_modules\thread-loader\dist\cjs.js:3
import index from './index.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at loadLoader (D:\Project\CTG\kv-retail-report-widget-3\node_modules\loader-runner\lib\loadLoader.js:19:17)
    at iteratePitchingLoaders (D:\Project\CTG\kv-retail-report-widget-3\node_modules\loader-runner\lib\LoaderRunner.js:182:2)

webpack 5.97.1 compiled with 1 error in 5170 m`

**Comment by alexander-akait** [comment]
@lelelethu Sorry for delay, do you still have a problem? Can you create reproducible test repo?
