### ISSUE TITLE
add loaderContext._compiler, is important 

### ISSUE THREAD

**Issue by crayon-shin-chan** [webpack-contrib/thread-loader#27]
awesome-typescript-loader need access loaderContext._compiler

TypeError: Cannot read property 'parentCompilation' of undefined
    at Object.getRootCompiler (/home/czy/桌面/react-demo/node_modules/awesome-typescript-loader/src/instance.ts:67:15)
    at compiler (/home/czy/桌面/react-demo/node_modules/awesome-typescript-loader/src/index.ts:42:23)
    at Object.loader (/home/czy/桌面/react-demo/node_modules/awesome-typescript-loader/src/index.ts:16:12)
    at LOADER_EXECUTION (/home/czy/桌面/react-demo/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/home/czy/桌面/react-demo/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/home/czy/桌面/react-demo/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at /home/czy/桌面/react-demo/node_modules/loader-runner/lib/LoaderRunner.js:202:4

**Comment by crayon-shin-chan** [comment]
normal build time  is 5000ms

if  i  do  it like this：
        webpack: true,
        'thread-loader': true
        sourceMap: data.sourceMap,
        _compiler: new Compiler(process.cwd())
it will waste more  time , 15000ms

**Comment by crayon-shin-chan** [comment]
if it means  threads must share one Compiler?

**Comment by lishichao1002** [comment]
+1

**Comment by alexander-akait** [comment]
`loaderContext._compiler` is private API, we partially support it, only main things, we can't pass all `loaderContext._compiler` to another thread
