### ISSUE TITLE
does not find loader-runner when using Yarn PnP

### ISSUE THREAD

**Issue by DanielRuf** [webpack-contrib/thread-loader#32]
```
Error: Cannot find module 'loader-runner'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/druf/Library/Caches/Yarn/v3/npm-thread-loader-1.2.0-35dedb23cf294afbbce6c45c1339b950ed17e7a4/node_modules/thread-loader/dist/worker.js:11:21)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
internal/modules/cjs/loader.js:583
    throw err;
    ^
```

**Comment by michael-ciniawsky** [comment]
Did you add https://github.com/arcanis/pnp-webpack-plugin to your config?

**Comment by DanielRuf** [comment]
> Did you add [arcanis/pnp-webpack-plugin](https://github.com/arcanis/pnp-webpack-plugin) to your config?

Was this referenced / mentioned somewhere?
Might be better to have PnP support in thread-loader and webpack in general.

**Comment by arcanis** [comment]
Can you make a quick repro PR on the [pnp-sample-app](https://github.com/yarnpkg/pnp-sample-app) repository? I'll give it a look and can tell you what's breaking, and once it's fixed we can merge the PR as an example 🙂

**Comment by arcanis** [comment]
As for the PnP Webpack plugin, it's currently needed as [enhanced-resolve](https://github.com/webpack/enhanced-resolve/tree/master/lib) doesn't yet have out-of-the-box support for PnP.

**Comment by DanielRuf** [comment]
> Can you make a quick repro PR on the [pnp-sample-app](https://github.com/yarnpkg/pnp-sample-app) repository? I'll give it a look and can tell you what's breaking, and once it's fixed we can merge the PR as an example 🙂

I'll check it this week and see if I can provide a PR to reproduce it in the playground repository.
