### ISSUE TITLE
EPIPE: broken pipe and sometimes ERR_STREAM_DESTROYED when Sending Ctrl+C (SIGINT)

### ISSUE THREAD

**Issue by mistic** [webpack-contrib/thread-loader#39]
Hello guys,

Sometimes when starting a webpack compilation from the webpack node api, stopping it in the middle with a `Ctrl+C (SIGINT)` generates the following error output for every spawned worker: 

```
{ [Error: EPIPE: broken pipe, write] errno: -32, code: 'EPIPE', syscall: 'write' }
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:406:19)
    at clearBuffer (_stream_writable.js:517:5)
    at WriteStream.Writable.uncork (_stream_writable.js:314:7)
    at /Users/tiago/test_project/node_modules/thread-loader/dist/worker.js:58:22
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

Then the process just hangs until I send a new `Ctrl+C`. Any plans/idea to solve this @evilebottnawi @sokra ? It seems related to https://github.com/webpack-contrib/thread-loader/issues/33 and https://github.com/webpack-contrib/thread-loader/pull/36

**Comment by mistic** [comment]
I'll close this issue as this is solved by https://github.com/webpack-contrib/thread-loader/pull/36
