### ISSUE TITLE
Issues with Postcss-Loader

### ISSUE THREAD

**Issue by ravencrown** [webpack-contrib/thread-loader#96]
Are there any known issues with postcss loader and the thread loader?

I am getting the following error:

```
ERROR in ./view/less/_export.less (./node_modules/thread-loader/dist/cjs.js??ref--6-2!./node_modules/css-loader/dist/cjs.js??ref--6-3!./node_modules/postcss-loader/src??ref--6-4!./node_modules/less-loader/dist/cjs.js??ref--6-5!./node_modules/style-resources-loader/lib??ref--6-6!./view/less/_export.less)
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 11)
Cannot read property 'postcss' of null
    at PoolWorker.fromErrorObj (/Users/chenguangxiao/Workspace/DMP/dmp-web/node_modules/thread-loader/dist/WorkerPool.js:262:12)
    at /Users/chenguangxiao/Workspace/DMP/dmp-web/node_modules/thread-loader/dist/WorkerPool.js:204:29
    at mapSeries (/Users/chenguangxiao/Workspace/DMP/dmp-web/node_modules/neo-async/async.js:3625:14)
    at PoolWorker.onWorkerMessage (/Users/chenguangxiao/Workspace/DMP/dmp-web/node_modules/thread-loader/dist/WorkerPool.js:170:35)
    at readBuffer (/Users/chenguangxiao/Workspace/DMP/dmp-web/node_modules/thread-loader/dist/WorkerPool.js:152:14)
    at Socket.onChunk (/Users/chenguangxiao/Workspace/DMP/dmp-web/node_modules/thread-loader/dist/readBuffer.js:36:9)
    at Socket.emit (events.js:198:13)
    at Processor.normalize (/Users/chenguangxiao/Workspace/DMP/dmp-web/node_modules/postcss/lib/processor.js:157:13)
    at new Processor (/Users/chenguangxiao/Workspace/DMP/dmp-web/node_modules/postcss/lib/processor.js:52:25)
    at postcss (/Users/chenguangxiao/Workspace/DMP/dmp-web/node_modules/postcss/lib/postcss.js:55:10)
    at Promise.resolve.then.then (/Users/chenguangxiao/Workspace/DMP/dmp-web/node_modules/postcss-loader/src/index.js:140:12)
 @ ./view/less/_export.less 2:26-335 43:4-64:5 46:18-327
 @ multi ./view/less/_export.less ./src/index
```

My usage looks like
```

const threadLoader = require('thread-loader')
const cssWorkerPool = {
  workerParallelJobs: 2,
  poolTimeout: 2000,
}
threadLoader.warmup(cssWorkerPool, [
  'cache-loader',
  'style-loader',
  'css-loader',
  'postcss-loader',
  'less-loader',
  'style-resources-loader',
])


    {
        test: /\.(le|c)ss$/,
        use: [
          {
            loader: 'cache-loader',
          },
          {
            loader: 'style-loader',
          },
          {
            loader: 'thread-loader',
            options: cssWorkerPool,
          },
          {
            loader: 'css-loader',
            options: {
              url: true,
            },
          },
          {
            loader: 'postcss-loader',
            options: {
              plugins: [require('postcss-cssnext')],
            },
          },
          {
            loader: 'less-loader',
            options: { paths: [pathUtil.resolve('/', 'node_modules')] },
            // options: {
            //   javascriptEnabled: true
            // }
          },
          {
            loader: 'style-resources-loader',
            options: {
              patterns: pathUtil.resolve('view/less/pre', '_export.less'),
            },
          },
        ],
      },
```

**Comment by evilebottnawi** [comment]
Duplicate, problem with `less-loader`
